site_name: Netshoot
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.indexes
    - navigation.expand
    - navigation.path
    - navigation.sections
    - header.autohide
    - content.code.copy
    - content.code.select
    - content.code.annotate

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Guide:
      - guide/index.md
      - Install: guide/install.md
      - Nodes:
          - payload:
              - guide/payload.md
              - Payload File: guide/payload-file.md
      - Progress: guide/progress.md
      - Output: guide/out.md

  - Configurations:
      - Config: configuration/config.md
      - client: configuration/client.md
      - server: configuration/server.md
      - Client Nodes:
          - payload: configuration/client-nodes/payload.md
      - Server Nodes:
          - payload: configuration/server-nodes/payload.md
  - Other:
      - other/index.md
      - create-Payload-File: other/create-payloadfile.md

repo_url: https://github.com/sadeepa24/netshoot
repo_name: sadeepa24/netshoot
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - i18n:
      default_language: si
      docs_structure: folder
      languages:
        # - locale: en
        #   name: English
        - locale: si
          name: සින්හල
          default: true # Mark English as the default language
          build: true # Ensure this language is built
        #   build: true # Spanish should also be built
        # - locale: fr
        #   name: Français
        #   build: false # French will not be built (optional)

extra:
  i18n:
    languages:
      # - locale: en
      #   name: English
      - locale: si
        name: සින්හල
      # - locale: fr
      #   name: Français
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/DaRker_WoLF
  generator: false

copyright: Copyright &copy; 2025 sadeepa24. All rights reserved.
